### PR TITLE
Added a Dart logo in (Header) README.md file.

### PR DESCRIPTION
**Pull request by Pradumnasaraf**
**Changes**
Added a Dart logo in (Header) README.md file.
Image resource file link - https://github.com/dart-lang/site-shared/blob/master/src/_assets/image/dart/logo/64.png

**Before Changes**

**After Changes**

### CODE REVIEW

**Comment by Pradumnasaraf** [comment]
Hey, @lrhn need your presence here 😀.

**Comment by lrhn** [comment]
I'll defer to oither people on how we style things.

**Comment by mit-mit** [comment]
Thanks for the PR. I like the idea, but I think this is a bit fragile. `site-shared` is an implementation detail of the `dart.dev` website, and might change, which would break the logo here. Thus I don't think we should add this.

**Comment by Pradumnasaraf** [comment]
@mit-mit Thank you!, I totally agree and respect your clarification. But I still believe adding the logo to any documentation adds some flavor and engagement (Ya but not in the fragile way :). )

**Comment by Pradumnasaraf** [comment]
@mit-mit Thank you for the reply. I totally agree and respect your clarification. But I still believe adding the logo to any documentation adds some flavor and engagement (Ya but not in the fragile way :). )

**Comment by Pradumnasaraf** [comment]
Thanks! @kwalrath 
Is there any way you can remove the closing tag and change it to merged?
@mit-mit

**Comment by kwalrath** [comment]
> Thanks! @kwalrath
> Is there any way you can remove the Closed tag, and change it to merged?
> @mit-mit

Not sure what you mean... This PR's closed; the one for site-www is merged.

**Comment by Pradumnasaraf** [comment]
> > Thanks! @kwalrath
> > Is there any way you can remove the Closed tag, and change it to merged?
> > @mit-mit
> 
> Not sure what you mean... This PR's closed; the one for site-www is merged.

Sorry my bad, again Thank you for your reply.

**Pull request closed without merging**
