### PR TITLE
fixed some small errors in future-releases

### PR DESCRIPTION
**Pull request by 0xflotus**
While spoiling myself with exciting new dart features I found some small typo errors in the specs.

### CODE REVIEW

**Comment by mit-mit** [comment]
Most excellent, thanks @0xflotus! Would you mind syncing with master? There is a small conflict (a few files got moved to 2.3)

**Comment by 0xflotus** [comment]
> Most excellent, thanks @0xflotus! Would you mind syncing with master? There is a small conflict (a few files got moved to 2.3)

What is the cleanest way to do that? Merge dart-lang:master in 0xflotus:master?

**Comment by munificent** [comment]
Merging when files get renamed is always a pain in Git. You can try just merging, but that might leave you with two copies of the files — your changes in the old location and the new files at the new location without your fixes.

I'd give that a try, and if Git gets confused, just note that you may need to copy/paste your fixes over to the new path and then delete the files at the old location again. Thanks for the fixes!

**Comment by 0xflotus** [comment]
See #378

**Comment by munificent** [comment]
Thanks for rebasing!

**Pull request closed without merging**
