### PR TITLE
Fixed grammer , irregular repetition

### PR DESCRIPTION
**Pull request by divyanshbhadauria**
Fixed wrong repetition in sentence.

### CODE REVIEW

**Comment by divyanshbhadauria** [comment]
@googlebot I signed it !

**Comment by divyanshbhadauria** [comment]
@googlebot  I fixed it.

**Comment by divyanshbhadauria** [comment]
@googlebot I fixed it.

**Comment by divyanshbhadauria** [comment]
@googlebot I fixed it.

**Comment by mit-mit** [comment]
Closing as stale

**Pull request closed without merging**
