### PR TITLE
Resurrect old notes around class modifiers.

### PR DESCRIPTION
**Pull request by munificent**
Leaf mentioned that it might be useful to bring these notes back from the old evolution repo, so here they are. I didn't commit them directly because I wasn't sure if this was where you wanted and I wanted to make sure that Erik was OK with me putting his words out there.

What do you think?

### CODE REVIEW

**Comment by yjbanov** [comment]
What a fantastic document! Creates a solid framework for thinking about class capabilities. However, I couldn't tell what the resolution is for the "can extend + can implement + private methods" issue. If I have control over my class' capabilities, then the compiler should flag the case when my class allows `implements` but makes it impossible to actually implement it due to private methods accessed from outside the class.

**Comment by eernstg** [comment]
LGTM!

**Comment by lrhn** [comment]
I'm split on whether I'd prefer this as an *issue* to encourage discussion, instead of a dead document that is stored by itself.

Discuss! :)

**Comment by munificent** [comment]
> If I have control over my class' capabilities, then the compiler should flag the case when my class allows implements but makes it impossible to actually implement it due to private methods accessed from outside the class.

Ah, that's interesting. It would be nice for the tools to give better guidance here.

> I'm split on whether I'd prefer this as an issue to encourage discussion, instead of a dead document that is stored by itself.

I'm going to go ahead and land it if that's OK. I think it's a non-goal to start a live discussion on this because, as far as I know, we aren't currently planning to take action on it. When/if we do, we can start a thread then and point to the doc.

**Pull request merged**
