### PR TITLE
Move wildcard variables into accepted.

### PR DESCRIPTION
**Pull request by kallentu**
Wildcard variables are almost fully implemented at this point. We should probably move it into accepted?

### CODE REVIEW

**Comment by lrhn** [comment]
Consider leaving a forwarding stub.  Just something like:
```md
# Wildcard variables feature specification

The feature is accepted and the accepted specification has been 
[moved](../../accepted/future-releases/wildcard-variables/feature-specification.md)
to the accepted features folder.
```

**Review by lrhn — APPROVED** [review]
LGTM, ship it!

**Review by eernstg — APPROVED** [review]
LGTM

**Comment by kallentu** [comment]
Added a forwarding stub, thanks @lrhn.

**Pull request merged**
