### PR TITLE
Move unnamed-libraries to 2.19 release

### PR DESCRIPTION
**Pull request by parlough**
[Dart 2.19](https://github.com/dart-lang/sdk/blob/main/CHANGELOG.md#2190---2023-01-24) included support for unnamed libraries.

### CODE REVIEW

**Comment by kevmoo** [comment]
@srawlins – I think you approve and land this. Tis your spec work!

**Comment by leafpetersen** [comment]
We have generally not done so when we move from future-releases to the appropriate release folder - it starts to get very cluttered.  We could consider leaving forwarding pointers in the README.md or somewhere else.

I do usually grep the rest of the repository for cross links to update.

**Comment by parlough** [comment]
I didn't find any other internal links to the directory or feature specification.

I pushed a potential README that we could leave behind, following a format similar to one found in the `working` directory. It might get cluttered, but perhaps they can be left temporarily. We have had multiple issues with feature-specifications links breaking on dart.dev when released, so there's definitely value in keeping a forwarding link for a certain period of time.

**Comment by parlough** [comment]
Superseded by https://github.com/dart-lang/language/pull/2983

**Comment by munificent** [comment]
Oops, sorry I didn't see this.

**Pull request closed without merging**
